### ISSUE TITLE
RocketMQ 集群部署 java.lang.RuntimeException: Lock failed,MQ already started 解决笔记

### ISSUE THREAD

**Issue by Shellbye** [Shellbye/Shellbye.github.io#69]
### 问题描述
`RocketMQ` 单机是比较容易配置的，基本上是拆箱即用，按照很多网络上的说法，集群部署也是非常简单，当然，说简单的应该是机器资源比较充沛的人，本周我在两条机器上交叉部署双主双从时，在启动了 `broker` 的的机器 B 上尝试启动机器 A 的 slave 节点时，启动报错如下
```
java.lang.RuntimeException: Lock failed,MQ already started
    at org.apache.rocketmq.store.DefaultMessageStore.start(DefaultMessageStore.java:220)
    at org.apache.rocketmq.broker.BrokerController.start(BrokerController.java:826)
    at org.apache.rocketmq.broker.BrokerStartup.start(BrokerStartup.java:64)
    at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58)
```
### 解决方案
在查阅了网上一些[资料](https://www.cnblogs.com/javashare/p/10052736.html)之后，发现是`RocketMQ`的存储路径冲突造成的，直接的解决方案就是在 `broker` 的配置文件中添加如下配置
```
storePathRootDir = /some/new/path/
```
这样就可以解决这个问题了。

**Comment by pencilso** [comment]
我把同一个机器上的master、slave 的storePathRootDir路径改为了不同的路径，但是也还是会出现这个错误。

**Comment by yeshucheng** [comment]
我也改过地址，依然也是偶尔出这个问题。不过我是三主三从  三个机器上装

**Comment by oniubi** [comment]
> 我把同一个机器上的master、slave 的storePathRootDir路径改为了不同的路径，但是也还是会出现这个错误。

我也是，路径全改为不相同了，还是报错：
/opt/rocketmq/bin/mqbroker: 48: [[: not found
java.lang.RuntimeException: Lock failed,MQ already started
